### ISSUE TITLE
Opening an LTN combinator with an LTN combinator already open

### ISSUE THREAD

**Issue by credomane** [kryojenik/LTN_Combinator_Modernized#1]
Steps to reproduce:
1. Open LTN Combinator.
2. With first still open; open another LTN combinator.
3. lua script crash results.

https://imgur.com/7y2e9Ql

**Comment by kryojenik** [comment]
This issue is limited to the 8.x train supporting Factorio 1.0.

The crash would also occur when 'opening' the same combinator that was already open.  It didn't have to be a different one.
