### ISSUE TITLE
enhancement request : Stacks available for requester

### ISSUE THREAD

**Issue by LoneWolfProductions** [kryojenik/LTN_Combinator_Modernized#10]
Would it  be possible to add an option to instead telling how many items i want. i say how many stacks i want?

I'm playing Pyanodons, and there are so many items with different stacksizes.

Looking over the code i see you already use then command

`stack_size = game.item_prototypes[signal.signal.name].stack_size`
in gui .lua on line 240

so i think it would be possible to set an item in a requester and telling a stack number instead of then negative number of items. by checking a check box tht would switch between item and stacks (for the slider under the output section)?

I really like the combinator. it takes away many annoying steps to set up a station
But needing to lookup every stack size and multiply it by the available slots is the biggest hassle.

So I think that the code could look at the requested item, find the stack size (if not fluid) and do the calculation for us with the number of slots we have/want?

**Comment by kryojenik** [comment]
Absolutely.   This was my intention when I started work on the slider aspect of it.   Definitely on the roadmap.

As it stands now, the slider actually moves in increments of stack size.  Admittedly, the resolution of the slider makes it hard to manage that way.

**Comment by LoneWolfProductions** [comment]
I noticed that, but like you said its hard to manage (and my requests are bigger then 256 stacks :p) but i know for eample that my station has 300 slots availbe that i want filled.
so if i could say 
*choose iron plate in output signal
and in the textbox put 300
the combinator would look and go like (simple example)
`(ironplate.stacksize * 300) * -1`

i think (not sure) by adding a checkbox to turn the number from "items wanted" to "stacks wanted" is the easiest way to go?
or a second input field? one for items one for stacks?
and the item filed would take privelege over the stack field if both are filled in?

just trying to give some ideas to work with  :D

**Comment by LoneWolfProductions** [comment]
YES, Thank you so much, no more calculation diferrent stack sizes :p
