### ISSUE TITLE
Multiplayer Concurrent Opening of Menu for different players leads to wrong assignment

### ISSUE THREAD

**Issue by Blackclaws** [kryojenik/LTN_Combinator_Modernized#17]
This issue already existed for the old version and it unfortunately still exists in the modernized version.

Using this combinator in multiplayer leads to very weird behaviour. The player opening the window last sets the combinator which will be modified by all other players open windows. This leads to players setting requests for the wrong stations.

**Comment by Blackclaws** [comment]
Messages like LTN Combinator: The combinator you are trying to adjust isn't there!

also pop up if multiple players open combinators and another player closes the window

**Comment by kryojenik** [comment]
Yes, this is a hold-over from some of the legacy code. I've been meaning to do a re-write of it so I can address this. Life (and my first Angel's) run has distracted me.

Thanks for the report, and I will refocus some attention on this in the near future.

https://mods.factorio.com/mod/LTN_Combinator_Modernized/discussion/60f1f7a322455e0170e2d9c6

**Comment by kryojenik** [comment]
> Messages like LTN Combinator: The combinator you are trying to adjust isn't there!
> 
> also pop up if multiple players open combinators and another player closes the window

This one _should_ only happen if the actual combinator you have open gets removed (or replaced).  I put this in as a more graceful than crash way of handling some of the concurrent open issues.  However, if it is happening in a situation where one of the players did NOT remove the combinator, or it didn't get destroyed, I would like to hear about repro steps.

**Comment by kryojenik** [comment]
The root of the issue here is that synchronization between multiple users with an open UI wasn't implemented by the original author.  Some base framework needs to be overhauled.

**Comment by Blackclaws** [comment]
I think it might be related to this:

https://github.com/kryojenik/LTN_Combinator_Modernized/blob/ebb074f7d90af1bf3ec0c49e28dd2cd5b46763d4/script/ltn-combinator.lua#L28

Where you might actually want to reference the new obj instead of self. The rest of the code looks like you are already segmenting by player index but here it appears as though you might be overriding the entity value stored in the ltn_combinator metatable.

**Comment by Blackclaws** [comment]
Synchronizing between users is secondary to the fact that if two players open two _different_ combinators one player starts writing into the signals of the other player without ever having opened that.

Repro steps for the error message are easy:

1. First player opens a combinator that has output signals set (such as advanced circuits or something similar)
2. Second player opens empty combinator
3. First player clicks on the output signal which is set 
4. Error message appears

This is the same underlying issue that the global entity that both players are referencing is the same.

You can also see this by doing the following:

1. Set up two combinators where one has in the first slot a signal with say 1000 as output, the second one has 10000
2. Player One opens first combinator
3. Player Two opens second cominator
4. Player One now clicks on the item, bottom bar will be populated with 10000 instead of 1000

**Comment by kryojenik** [comment]
fixed by 52c5ec2
