### ISSUE TITLE
LTN Network-ID is not always sent to combinator output

### ISSUE THREAD

**Issue by nicolas-lang** [kryojenik/LTN_Combinator_Modernized#19]
While I can set the network-ID and it also persists during GUI-reopening, it does not affect the output value.
![image](https://user-images.githubusercontent.com/635895/136272113-1d12fa2b-d441-4140-a1bd-ad5f190fc4dd.png)
( I have opened and closed the GUI and it did not change values)

v 1.0.7 / heavy modded multiplayer game / (very laggy as I am currently on hotel Wifi)

Update: I can fix the issue by changeing the network ID to fro example 1+2, and then change back to 2

**Comment by kryojenik** [comment]
Probably not emitting a signal since it is the configured 'default' network.  Since there was no response with additional detail and I have been unable to reproduce a similar issue I'll mark this as closed.   If someone sees something else, please provide deatils.

**Comment by nicolas-lang** [comment]
I have not encountered this issue any more after the initial problem and I wasn't able to force it to appear again either.
(I haven't spent much time playing factorio in the past weeks, sorry for the late reply.)

Agree with /close
