### ISSUE TITLE
"E" key doesn't close LTN combinators.

### ISSUE THREAD

**Issue by credomane** [kryojenik/LTN_Combinator_Modernized#2]
It seems like it should work as the first press of "E" after opening a LTn combinator does nothing but all following presses open/close the inventory while the LTN combinator stays open in the background. The "ESC" key works to close the LTN combinator. Looking at the source code it looks like they should both work the exact same way and this might be an issue in Factorio 1.0 only. Factorio 1.1.0 renamed "Close Window" to "confirm GUI" and this certainly changed the name of the "linked_game_control" option as well.

If it ends up just being the name change between 1.0 and 1.1 maybe just ignore this issue as 1.1 it going stable soon. One of the devs is hoping this week as the last few releases have all been release candidates.

**Comment by kryojenik** [comment]
Issue is limited to the 8.x train supporting Factorio 1.0.  The linked control 'close-gui' was changed to 'confirm-gui' in 1.1.  Made accommodations for 1.0.
