### ISSUE TITLE
Locked slots per wagon capped at 40.

### ISSUE THREAD

**Issue by TheCadde** [kryojenik/LTN_Combinator_Modernized#23]
Is there an invalid assumption in code here?
Locked slots per wagon cannot be set any higher than 40, even though there are wagons in the wild that accept more than 40 slots of cargo.

I find that overzealous massaging of user input can be detrimental. Please stick to the rules of LTN only and don't set other values willynilly because it just leads to frustrations.

**Comment by kryojenik** [comment]
Yeah, that's a reasonable ask.  Next version will allow setting to the max size of the largest cargo-wagon.
