### ISSUE TITLE
 Combinators starting enabled

### ISSUE THREAD

**Issue by Dominiquini** [kryojenik/LTN_Combinator_Modernized#30]
The new version, even when I configured the combinator to always start disabled, it always start enabled!

Thanks

**Comment by kryojenik** [comment]
I addressed this on the discussion forum.  The "disabled" referes to setting a high threshold for the requester and provider services.  The setting you choose in mod-settings will set the approriate high threshold and uncheck the provider and requester boxes when built.  The combinator will remain "On".
