### ISSUE TITLE
Crash on dedicated server when setting request value to empty

### ISSUE THREAD

**Issue by Bluedot55** [kryojenik/LTN_Combinator_Modernized#43]
Ran into a crash. If I remember correctly, I had just tried to set an item to an empty stack size limit for a requester. 

`249227.443 Error MainLoop.cpp:1288: Exception at tick 10921398: The mod LTN Combinator Modernized (2.0.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Combinator_Modernized::on_gui_click (ID 1)
LTN_Combinator_Modernized/script/ltn_combinator.lua:606: attempt to index field 'elem_value' (a nil value)
stack traceback:
    LTN_Combinator_Modernized/script/ltn_combinator.lua:606: in function 'handler'
    LTN_Combinator_Modernized/script/ltn_combinator.lua:833: in function 'wrapper'
    flib/gui-lite.lua:139: in function 'handler'
    flib/gui-lite.lua:169: in function 'handler'
    core/lualib/event_handler.lua:47: in function <core/lualib/event_handler.lua:45>
249227.449 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod LTN Combinator Modernized (2.0.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Combinator_Modernized::on_gui_click (ID 1)
LTN_Combinator_Modernized/script/ltn_combinator.lua:606: attempt to index field 'elem_value' (a nil value)
stack traceback:
    LTN_Combinator_Modernized/script/ltn_combinator.lua:606: in function 'handler'
    LTN_Combinator_Modernized/script/ltn_combinator.lua:833: in function 'wrapper'
    flib/gui-lite.lua:139: in function 'handler'
    flib/gui-lite.lua:169: in function 'handler'
    core/lualib/event_handler.lua:47: in function <core/lualib/event_handler.lua:45>"
249227.452 Info ServerMultiplayerManager.cpp:797: updateTick(10921398) changing state from(InGame) to(Failed)
249227.458 Quitting: multiplayer error.
249228.780 Info ServerMultiplayerManager.cpp:141: Quitting multiplayer connection.
249228.782 Info ServerMultiplayerManager.cpp:797: updateTick(4294967295) changing state from(Failed) to(Closed)
249229.210 Info UDPSocket.cpp:218: Closing socket
249229.211 Info UDPSocket.cpp:248: Socket closed
249229.221 Goodbye`

**Comment by kryojenik** [comment]
Fixed by 20871ab4.

Also in this commit is making sure the edit controls get disabled when changing the Request/Provide/Depot checkboxes before commiting a miscellaneous signal.  Leving the confirm button enabled when the partially setup signal is now invalid - leading to  a crash upon clicking confirm.

**Comment by kryojenik** [comment]
For posterity, the exact repro steps are:

Click on a signal button to create a request (do not click confirm or type enter)
Click on a Provider / Requester / Depot check box
Finally, click on the confirn button that is still enabled (but now no request signal is being set up)
Crash
