### ISSUE TITLE
[2.1.1] The interface does not display signals correctly

### ISSUE THREAD

**Issue by m4a1j9** [kryojenik/LTN_Combinator_Modernized#49]
Reproduce:
1. Set up the combinator to depot and connect it to the train station
![image](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/88237046/7c03883e-254e-4d4b-bad4-c0878c35b820)
![image](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/88237046/0375e39f-0658-4917-9d08-b84b164ab056)

2. Create another provide/request station with combinator and copy it
![image](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/88237046/a72304d9-9b09-4698-b8df-5d53c65c401b)
![image](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/88237046/f6f8f24a-6916-404e-a67e-979ebe7894e8)

3. Past the blueprint on the existing one
![image](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/88237046/a035bcbf-0032-4bdf-8bda-5383f36de542)
![image](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/88237046/19f9d38b-1f1d-4ff4-815d-2a8c00096810)

(Game version: 1.1.87)

The problem:
In result we have a combinator that actually emits the same signals as the one we copied. But when we open its interface, its values correspond to the combinator that stood in this cell before. Interestingly, this only applies to the request/provider parameters.

Expected behavior:
When placing a combinator by blueprint, the existing one should display the new parameters.

I hope you find some time to consider the source of the problem, thx for your time and helpful mod!

P.S.: Idk if this is normal behavior or not, but in older versions of the mod everything worked as I expected. And I apologize for my english - it's not perfect)

**Comment by kryojenik** [comment]
Thanks for the report! I have confirmed / replicated this issue and I'm working on a fix.
