### ISSUE TITLE
Output Signals are always Negative

### ISSUE THREAD

**Issue by Shrugger** [kryojenik/LTN_Combinator_Modernized#51]
![image](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/10573055/4b854705-75f6-4bff-880d-879cccf5e313)

Regardless of whether using the slider or the input field, any value entered will turn into a negative output.

**Comment by kryojenik** [comment]
This is expected behavior.  You can either hold shift when clicking the green "Apply" (check-mark) button to keep the numbers positive.   Hover the mouse over the green button to see the Tool-tip.  There is also a mod-setting to adjust this behavior.
