### ISSUE TITLE
Dedicated server crash: attempt to index local 'ws' (a nil value)

### ISSUE THREAD

**Issue by JDouven** [kryojenik/LTN_Combinator_Modernized#54]
We've observed this crash on our dedicated server. This happened when copy/pasting train stations with combinators. There were 2 players in the area and I think both were interacting with the combinators. I'm not sure when **exactly** this happened. It has only happened once so far.

```
959858.791 Error MainLoop.cpp:1404: Exception at tick 12403392: The mod LTN Combinator Modernized (2.1.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LTN_Combinator_Modernized::on_gui_text_changed (ID 2)
__LTN_Combinator_Modernized__/script/util.lua:40: attempt to index local 'ws' (a nil value)
stack traceback:
        __LTN_Combinator_Modernized__/script/util.lua:40: in function 'from_stacks'
        __LTN_Combinator_Modernized__/script/ltn_combinator.lua:755: in function 'handler'
        __LTN_Combinator_Modernized__/script/ltn_combinator.lua:968: in function 'wrapper'
        __flib__/gui-lite.lua:139: in function 'handler'
        __flib__/gui-lite.lua:169: in function 'handler'
        __core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
```

I'd be happy to contribute a fix for this, but I'm not familiar enough with the mod's code to be able to understand what is going wrong here.

**Comment by kryojenik** [comment]
I don't know that I've seen this reproduce.  If it is still happening and you have a save file with some reproduction steps I'd be happy to look at it.  However, with LTN not getting ported to 2.0 I'm not sure there is much value in a fix here.  Let me know.

**Comment by kryojenik** [comment]
Closing this out before I archive the repo.
