### ISSUE TITLE
Automatic request recalculation

### ISSUE THREAD

**Issue by VladislavPrimakov** [kryojenik/LTN_Combinator_Modernized#55]
Many modpacks have several tiers of wagons with different numbers of stacks, and I had an idea of how to adapt to this. Automatically recalculate requests in the LTN combinator after changing the size of one wagon.
The picture roughly outlines what it might look like.
And it turns out that you need to indicate how many full wagons of some item to request at the station and with each range of the pasture it will recalculate everything.
![None](https://github.com/kryojenik/LTN_Combinator_Modernized/assets/61202829/465b18f6-9156-4837-86bf-43e94d4317a3)

**Comment by kryojenik** [comment]
Don't plan on adding new features since LTN will not be getting ported to 2.0
