### ISSUE TITLE
Support for virtual signals for network selector

### ISSUE THREAD

**Issue by annapoulakos** [kryojenik/LTN_Combinator_Modernized#56]
I was trying to set networks to use mod-based virtual signals (LTN, Schall's, Dectorio, Nixie Tubes, etc) but it just does not seem to do anything. I am able to put any of the vanilla signals in (as far as I can tell anyways), but virtual signals added from other mods do not seem to work (at least in my limited testing).

I don't do much Lua development these days, so I am not where in your code the icon is being set. I thought it might be here https://github.com/kryojenik/LTN_Combinator_Modernized/blob/ad841e69e4966a73e3fd3a24ae3fd62087436ead/script/network_descriptions.lua#L10 but I am not certain of that. 

I don't mind making a PR to update this if you could point me in the right direction.

Thanks!

**Comment by kryojenik** [comment]
Are you referring to the the Icon displayed on the network button, or as an icon embedded in the description text?

**Comment by annapoulakos** [comment]
The icons when you select the network button.

Basically, I click the combinator, then shift click one of the network ID's. After selecting an icon and clicking the green check button, they are not showing up for any of the custom virtual signals. Additionally, it seems that the number icons are also not appearing.

![image](https://github.com/user-attachments/assets/7aa3557b-c3db-4449-a142-8f51fa7f48c1)

**Comment by annapoulakos** [comment]
Thanks for this! You rock!
