### ISSUE TITLE
Hi, it's time for you to get busy, LTN has been ported to 2.0

### ISSUE THREAD

**Issue by Masturbio228** [kryojenik/LTN_Combinator_Modernized#57]
https://github.com/PSR-J0740/Logistic-Train-Network

**Comment by kryojenik** [comment]
Awesome!   I've somewhat following their progress as well.  I will keep a closer eye on it.  @cablegunmaster has done some work on the combinator already.  Will definitely look there and see what makes sense to carry forward as well.

I do have a few things in play at the moment and will get to this as soon as I can!

**Comment by Masturbio228** [comment]
Very much looking forward to it and best wishes for success)

**Comment by kryojenik** [comment]
Closing this out again.  Porting of LTN to 2.0 still doesn't look like it will happen.
